{{- if .Values.adaptor.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adaptor.fullname }}
  labels:
    rainbond: adaptor
spec:
  replicas: 1
  selector:
  {{- with .Values.adaptor.selectorLabels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  template:
    metadata:
    {{- with .Values.adaptor.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.adaptor.selectorLabels }}
      labels:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      containers:
        - name: adaptor
          image: "{{ .Values.adaptor.image.repository }}:{{ .Values.adaptor.image.tag }}"
          imagePullPolicy: {{ .Values.adaptor.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: rainbond-mysql-secret
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: BUILD_PROCFILE
              value: "web: bin/cloud-adaptor daemon"
            - name: CHART_PATH
              value: "/app/chart"
            - name: CONFIG_DIR
              value: "/app/data/cloudadaptor"
            - name: HELM_CACHE
              value: "/app/helmcache/cache"
            - name: HELM_PATH
              value: "/app/helm"
            - name: HELM_REPO_FILE
              value: "/app/helmcache/repo/repository.yaml"
            - name: LISTEN
              value: "0.0.0.0:8080"
            - name: DB_TYPE
              value: mysql
            - name: MYSQL_HOST
              value: "{{ .Values.mysql.fullname }}"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_PASS
              value: "$(MYSQL_PASSWORD)"
          ports:
            - name: tcp
              containerPort: 8080
              protocol: TCP
          volumeMounts:
          - mountPath: /app/data
            name: adaptor-data
          - mountPath: /app/.ssh
            name: adaptor-ssh
          resources:
            {{- toYaml .Values.adaptor.resources | nindent 12 }}
      volumes:
      - name: adaptor-data
        persistentVolumeClaim:
          claimName: rainbond-adaptor-pvc-data
      - name: adaptor-ssh
        persistentVolumeClaim:
          claimName: rainbond-adaptor-pvc-ssh
      {{- with .Values.adaptor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.adaptor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}