apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.fullname }}-secret
  labels:
    rainbond: mysql-secret
type: Opaque
data:
  MYSQL_USER: {{ .Values.mysql.secret.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysql.secret.password | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secret.rootpassword | b64enc }}
  MYSQL_DATABASE: {{ .Values.mysql.secret.database | b64enc }}
